# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import os
from pathlib import Path  # 在文件开头添加导入
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import (Qt, QTimer, QTimer, QMimeData, QPoint, QUrl)  # 从 QtCore 导入 QUrl
from PyQt5.QtGui import (QPixmap, QPainter, QDrag)
from PyQt5.QtWidgets import (QComboBox, QAbstractItemView, QApplication, QTableWidget)
                           

class CustomComboBox(QComboBox):
    """重写QComboBox类, 保证用户点击复选框时不立即收起"""

    def __init__(self, parent=None):
        super(CustomComboBox, self).__init__(parent)
        self.setEditable(True)  # 设置可编辑

    def mousePressEvent(self, event):
        """处理鼠标点击事件"""
        if self.view().isVisible() and self.view().underMouse():
            event.accept()  # 点击下拉框区域时，接受事件并保持展开
        else:
            super(CustomComboBox, self).mousePressEvent(event)  # 调用父类的默认行为进行下拉框关闭

    def hidePopup(self):
        """自定义 hidePopup 方法，控制下拉框隐藏"""
        if self.view().isVisible() and not self.view().underMouse():
            super(CustomComboBox, self).hidePopup()


class DraggableTableWidget(QTableWidget):
    def __init__(self, parent=None):
        super().__init__(parent)
        self.drag_start_position = None
        self.temp_files = set()
        self.main_window = None  # 添加主窗口引用
        
        # 设置拖拽相关属性
        self.setDragEnabled(True)
        self.setSelectionMode(QAbstractItemView.ExtendedSelection)
        self.setDragDropMode(QAbstractItemView.DragOnly)
        self.setAcceptDrops(False)
        
        # 设置清理临时文件的定时器
        self.cleanup_timer = QTimer()
        self.cleanup_timer.timeout.connect(self.clean_temp_files)
        self.cleanup_timer.start(600000)

    def set_main_window(self, main_window):
        """设置主窗口引用"""
        self.main_window = main_window

    def mousePressEvent(self, event):
        if event.button() == Qt.LeftButton:
            item = self.itemAt(event.pos())
            if item:
                self.drag_start_position = event.pos()

        super().mousePressEvent(event)

    def mouseMoveEvent(self, event):
        """重写鼠标移动事件，支持拖拽功能切换"""
        # 提前检查是否按下左键，避免不必要的判断
        if not (event.buttons() & Qt.LeftButton):
            return
            
        # 确保有起始拖拽位置
        if not self.drag_start_position:
            return
            
        # 计算拖拽距离，避免重复计算
        drag_distance = (event.pos() - self.drag_start_position).manhattanLength()
        
        if self.main_window.drag_flag: # 主函数中定义的拖拽模式切换标志位

            if drag_distance < QApplication.startDragDistance():
                return
                
            selected_items = self.selectedItems()
            if not selected_items:
                return
                
            # 创建拖拽对象和MIME数据
            drag = QDrag(self)
            mime_data = QMimeData()
            
            # 收集文件URL
            urls = []
            for item in selected_items:
                file_path = self.get_file_path_from_item(item)
                if file_path and os.path.exists(file_path):
                    urls.append(QUrl.fromLocalFile(file_path))
                    
            if not urls:
                return
                
            mime_data.setUrls(urls)
            drag.setMimeData(mime_data)
            
            try:
                # 根据选择项数量创建不同的预览图
                if len(urls) == 1:
                    preview = QPixmap(urls[0].toLocalFile()).scaled(64, 64, Qt.KeepAspectRatio, Qt.SmoothTransformation)
                else:
                    preview = QPixmap(128, 128)
                    preview.fill(Qt.transparent)
                    
                    with QPainter(preview) as painter:
                        painter.setRenderHint(QPainter.Antialiasing)
                        
                        # 使用预定义的颜色和字体
                        bg_color = QtGui.QColor(128, 128, 128, 180)
                        text_color = QtGui.QColor(255, 255, 255)
                        
                        # 绘制背景
                        painter.setBrush(bg_color)
                        painter.setPen(Qt.NoPen)
                        painter.drawRoundedRect(0, 0, 128, 128, 8, 8)
                        
                        # 设置文本样式
                        font = QtGui.QFont()
                        font.setPointSize(12)
                        font.setBold(True)
                        painter.setFont(font)
                        
                        # 绘制文本
                        painter.setPen(text_color)
                        painter.drawText(preview.rect(), Qt.AlignCenter, f"{len(urls)}个文件")
                
                # 设置预览图
                drag.setPixmap(preview)
                drag.setHotSpot(QPoint(preview.width()//2, preview.height()//2))
                
                # 执行拖拽操作并清理临时文件
                drag_result = drag.exec_(Qt.CopyAction)
                if drag_result == Qt.IgnoreAction:
                    self.clean_temp_files()  # 拖拽失败时清理
                elif drag_result == Qt.CopyAction:
                    # 可选：拖拽成功后延迟清理临时文件
                    QTimer.singleShot(1000, self.clean_temp_files)
                    
            except Exception as e:
                print(f"拖拽操作失败: {e}")
                self.clean_temp_files()
                
        else:
            # 处理多选功能
            current_item = self.itemAt(event.pos())
            if not current_item:
                return
                
            start_item = self.itemAt(self.drag_start_position)
            if not start_item:
                return
                
            if event.buttons() & Qt.LeftButton:
                # 获取选择范围
                start_pos = (start_item.row(), start_item.column())
                current_pos = (current_item.row(), current_item.column())
                
                # 计算选择范围
                min_row, max_row = sorted([start_pos[0], current_pos[0]])
                min_col, max_col = sorted([start_pos[1], current_pos[1]])
                
                # 清除当前选择并选择新范围
                self.clearSelection()
                for row in range(min_row, max_row + 1):
                    for col in range(min_col, max_col + 1):
                        if item := self.item(row, col):
                            item.setSelected(True)

    def get_file_path_from_item(self, item):
        """从表格项获取文件路径"""
        try:
            if not self.main_window:
                print("错误：未设置主窗口引用")
                return None

            row = item.row()
            col = item.column()
            
            # 获取文件名
            file_name = item.text().split('\n')[0] if item else None
            if not file_name:
                return None
                
            # 获取列名
            header_item = self.horizontalHeaderItem(col)
            if not header_item:
                return None
            column_name = header_item.text()
            
            # 从主窗口获取当前目录
            current_directory = self.main_window.RT_QComboBox.currentText()
            if not current_directory:
                return None
                
            # 构建完整路径，传统方案
            # full_path = os.path.join(os.path.dirname(current_directory), column_name, file_name)
            # return full_path if os.path.isfile(full_path) else None

            # 使用 Path 构建路径
            full_path = Path(current_directory).parent / column_name / file_name
            return str(full_path) if full_path.is_file() else None
            
            
        except Exception as e:
            print(f"获取文件路径失败: {e}")
            return None
        
    def clean_temp_files(self):
        """清理临时文件"""
        for path in self.temp_files.copy():
            if os.path.exists(path):
                try:
                    os.remove(path)
                    self.temp_files.remove(path)
                except Exception as e:
                    print(f"清理临时文件失败: {e}")

    def __del__(self):
        """析构函数中清理所有临时文件"""
        self.clean_temp_files()

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        """设置主窗口"""
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(964, 669)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setSizeIncrement(QtCore.QSize(3, 3))
        MainWindow.setIconSize(QtCore.QSize(60, 60))
        MainWindow.setDocumentMode(False)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        MainWindow.setDockNestingEnabled(False)
        # 设置主窗口的主体
        self.main_body = QtWidgets.QWidget(MainWindow)
        self.main_body.setStyleSheet("")
        self.main_body.setObjectName("main_body")
        # 设置可扩展的大小策略
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        self.main_body.setSizePolicy(sizePolicy)
        # 允许 gridLayout 的子组件自由拉伸
        self.gridLayout = QtWidgets.QGridLayout(self.main_body)
        self.gridLayout.setObjectName("gridLayout")
        # self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        # self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        # 设置分割器
        self.splitter = QtWidgets.QSplitter(self.main_body)
        self.splitter.setSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        # 设置分割器不可折叠
        self.splitter.setChildrenCollapsible(False)
        self.splitter.setObjectName("splitter")

        """设置分割器左侧组件--磁盘显示self.Left_QGroupBox"""
        self.Left_QGroupBox = QtWidgets.QGroupBox(self.splitter)
        self.Left_QGroupBox.setMinimumSize(QtCore.QSize(0, 0))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        self.Left_QGroupBox.setSizePolicy(sizePolicy)  # 将大小策略应用到 QGroupBox
        self.Left_QGroupBox.setFlat(False)
        self.Left_QGroupBox.setCheckable(False)
        self.Left_QGroupBox.setObjectName("Left_QGroupBox")
        # 磁盘显示 里面套一个垂直layout1
        self.verticalLayout_left_1 = QtWidgets.QVBoxLayout(self.Left_QGroupBox)
        self.verticalLayout_left_1.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_left_1.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_left_1.setSpacing(5)
        self.verticalLayout_left_1.setObjectName("verticalLayout_left_1")
        # 垂直layout1 里面套一个QTreeView(pyqt中的类，用来显示树形结构的数据，展示文件系统、层级结构等)
        self.Left_QTreeView = QtWidgets.QTreeView(self.Left_QGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        self.Left_QTreeView.setSizePolicy(sizePolicy)
        self.Left_QTreeView.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Left_QTreeView.setObjectName("Left_QTreeView")
        # 磁盘显示 里面套一个QFrame框架容器
        self.Left_QFrame = QtWidgets.QFrame(self.Left_QGroupBox)
        self.Left_QFrame.setAutoFillBackground(False)
        self.Left_QFrame.setObjectName("Left_QFrame")
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)  # 设置为可扩展
        self.Left_QFrame.setSizePolicy(sizePolicy)
        # QFrame框架容器 里面套一个垂直layout2
        self.verticalLayout_left_2 = QtWidgets.QVBoxLayout(self.Left_QFrame)
        self.verticalLayout_left_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_left_2.setObjectName("verticalLayout_left_2")
        # 垂直layout2 里面套两个radioButton（显示文件和隐藏文件）
        self.L_radioButton1 = QtWidgets.QRadioButton(self.Left_QFrame)
        # self.L_radioButton1.setMinimumSize(QtCore.QSize(0, 0))
        self.L_radioButton1.setSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)  # 设置为可扩展
        self.L_radioButton1.setObjectName("L_radioButton1")
        self.verticalLayout_left_2.addWidget(self.L_radioButton1)
        self.L_radioButton2 = QtWidgets.QRadioButton(self.Left_QFrame)
        # self.L_radioButton2.setMinimumSize(QtCore.QSize(0, 0))
        self.L_radioButton2.setSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)  # 设置为可扩展
        self.L_radioButton2.setObjectName("L_radioButton2")
        self.verticalLayout_left_2.addWidget(self.L_radioButton2)
        # 将Left_QTreeView和Left_QFrame套在垂直layout1中，并设置拉伸因子
        self.verticalLayout_left_1.addWidget(self.Left_QTreeView)
        self.verticalLayout_left_1.addWidget(self.Left_QFrame)
        # 设置自由拉伸
        self.verticalLayout_left_1.setStretch(0, 10)  # 第一个组件的拉伸因子
        self.verticalLayout_left_1.setStretch(1, 0)   # 第二个组件的拉伸因子

        """设置分割器右侧组件"""
        self.Right_QFrame = QtWidgets.QFrame(self.splitter)
        self.Right_QFrame.setSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        self.Right_QFrame.setObjectName("Right_QFrame")
        # 设置右侧垂直layout
        self.Right_QVBoxLayout = QtWidgets.QVBoxLayout(self.Right_QFrame)
        self.Right_QVBoxLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.Right_QVBoxLayout.setContentsMargins(0, 0, 0, 0)
        self.Right_QVBoxLayout.setSpacing(0)
        self.Right_QVBoxLayout.setObjectName("Right_QVBoxLayout")


        """右侧控制界面"""
        self.Right_Top_QGroupBox = QtWidgets.QGroupBox(self.Right_QFrame)
        self.Right_Top_QGroupBox.setSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        self.Right_Top_QGroupBox.setObjectName("Right_Top_QGroupBox")

        # 控制界面 套一个水平layout1
        self.qhLayout_right_1 = QtWidgets.QHBoxLayout(self.Right_Top_QGroupBox)
        self.qhLayout_right_1.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.qhLayout_right_1.setContentsMargins(6, 5, 5, 5)
        self.qhLayout_right_1.setSpacing(5)
        self.qhLayout_right_1.setObjectName("qhLayout_right_1")

        # 垂直layout1 套一个 垂直layout
        self.RT_QVBoxLayout = QtWidgets.QVBoxLayout()
        self.RT_QVBoxLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.RT_QVBoxLayout.setObjectName("RT_QVBoxLayout")
        # 垂直layout1 再套一个 垂直layout2
        self.RT_QVBoxLayout2 = QtWidgets.QVBoxLayout()
        self.RT_QVBoxLayout2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.RT_QVBoxLayout2.setObjectName("RT_QVBoxLayout2")

        # 设置右侧第一行的 水平layout (被套在垂直layout self.RT_QVBoxLayout中)  
        self.RT_QHBoxLayout = QtWidgets.QHBoxLayout()
        self.RT_QHBoxLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.RT_QHBoxLayout.setSpacing(8)
        self.RT_QHBoxLayout.setObjectName("RT_QHBoxLayout1")

        # 右侧第一行带输入的下拉框
        self.RT_QComboBox = QtWidgets.QComboBox(self.Right_Top_QGroupBox)
        self.RT_QComboBox.setEditable(True)  # 设置 QComboBox 为可编辑状态
        self.RT_QComboBox.setSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        self.RT_QComboBox.setObjectName("RT_QComboBox")
        
        self.RT_Line1 = QtWidgets.QFrame(self.Right_Top_QGroupBox)
        self.RT_Line1.setFrameShape(QtWidgets.QFrame.VLine)
        self.RT_Line1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.RT_Line1.setObjectName("RT_Line1")
        
        # 清除按钮
        self.RT_QPushButton3 = QtWidgets.QPushButton(self.Right_Top_QGroupBox)
        self.RT_QPushButton3.setSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        self.RT_QPushButton3.setObjectName("RT_QPushButton3")
        

        # 设置右侧第二行的 水平layout
        self.RT_QHBoxLayout2 = QtWidgets.QHBoxLayout()
        self.RT_QHBoxLayout2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.RT_QHBoxLayout2.setSpacing(8)
        self.RT_QHBoxLayout2.setObjectName("RT_QHBoxLayout2")

        # 右侧第二行的四个下拉框
        self.RT_QComboBox0 = QtWidgets.QComboBox(self.Right_Top_QGroupBox)
        self.RT_QComboBox0.setSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        # self.RT_QComboBox0.setMinimumSize(QtCore.QSize(0, 30))
        self.RT_QComboBox0.setObjectName("RT_QComboBox0")
        
        # 使用自定义的下拉框
        self.RT_QComboBox1 = CustomComboBox(self.Right_Top_QGroupBox)
        self.RT_QComboBox1.setSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        # self.RT_QComboBox1.setMinimumSize(QtCore.QSize(0, 30))
        self.RT_QComboBox1.setObjectName("RT_QComboBox1")

        self.RT_QComboBox2 = QtWidgets.QComboBox(self.Right_Top_QGroupBox)
        self.RT_QComboBox2.setSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        # self.RT_QComboBox2.setMinimumSize(QtCore.QSize(0, 30))
        self.RT_QComboBox2.setObjectName("RT_QComboBox2")
        
        self.RT_QComboBox3 = QtWidgets.QComboBox(self.Right_Top_QGroupBox)
        self.RT_QComboBox3.setSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        # self.RT_QComboBox3.setMinimumSize(QtCore.QSize(0, 30))
        self.RT_QComboBox3.setObjectName("RT_QComboBox3")

        self.RT_QH2_line4 = QtWidgets.QFrame(self.Right_Top_QGroupBox)
        self.RT_QH2_line4.setFrameShape(QtWidgets.QFrame.VLine)
        self.RT_QH2_line4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.RT_QH2_line4.setObjectName("RT_QH2_line4")
        
        # 对比按钮
        self.RT_QPushButton5 = QtWidgets.QPushButton(self.Right_Top_QGroupBox)
        self.RT_QPushButton5.setSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        self.RT_QPushButton5.setObjectName("RT_QPushButton5")
        

        # 设置右侧第一行的 水平layout的拉伸比例
        self.RT_QHBoxLayout.addWidget(self.RT_QComboBox)
        self.RT_QHBoxLayout.addWidget(self.RT_Line1)
        
        self.RT_QHBoxLayout.setStretch(0, 8)
        # self.RT_QHBoxLayout.setStretch(1, 1)
        

        # 设置右侧第二行的 水平layout 的拉伸比例
        self.RT_QHBoxLayout2.addWidget(self.RT_QComboBox0)
        self.RT_QHBoxLayout2.addWidget(self.RT_QComboBox1)
        self.RT_QHBoxLayout2.addWidget(self.RT_QComboBox2)
        self.RT_QHBoxLayout2.addWidget(self.RT_QComboBox3)
        self.RT_QHBoxLayout2.addWidget(self.RT_QH2_line4)

        self.RT_QHBoxLayout2.setStretch(0, 2)
        self.RT_QHBoxLayout2.setStretch(1, 2)
        self.RT_QHBoxLayout2.setStretch(2, 2)
        self.RT_QHBoxLayout2.setStretch(3, 2)
        # self.RT_QHBoxLayout2.setStretch(4, 1)
        
        # 设置垂直layout包括两个按钮
        self.RT_QVBoxLayout2.addWidget(self.RT_QPushButton3)
        self.RT_QVBoxLayout2.addWidget(self.RT_QPushButton5)

        # 设置右侧控制界面—--左侧垂直layout包含两个水平layout
        self.RT_QVBoxLayout.addLayout(self.RT_QHBoxLayout)
        self.RT_QVBoxLayout.addLayout(self.RT_QHBoxLayout2)
        
        # 设置右侧控制界面---水平layout包含两个垂直layout
        self.qhLayout_right_1.addLayout(self.RT_QVBoxLayout)
        self.qhLayout_right_1.addLayout(self.RT_QVBoxLayout2)
        self.qhLayout_right_1.setStretch(0, 10)
        self.qhLayout_right_1.setStretch(1, 1)

        # 设置右侧--大的垂直layout包含控制界面
        self.Right_QVBoxLayout.addWidget(self.Right_Top_QGroupBox)
        
        """右侧显示界面"""
        self.Right_Bottom_QGroupBox = QtWidgets.QGroupBox(self.Right_QFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        self.Right_Bottom_QGroupBox.setSizePolicy(sizePolicy)
        self.Right_Bottom_QGroupBox.setObjectName("Right_Bottom_QGroupBox")

        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.Right_Bottom_QGroupBox)
        self.verticalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_3.setContentsMargins(6, 5, 5, 5)
        self.verticalLayout_3.setSpacing(1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")

        # 右侧第三行的表格组件,设置自定义或者默认模式
        # self.RB_QTableWidget0 = QtWidgets.QTableWidget(self.Right_Bottom_QGroupBox)
        # 使用自定义的表格，支持拖拽事件
        if self.drag_flag:
            self.RB_QTableWidget0 = DraggableTableWidget(self)
            # 设置表格的主窗口引用
            self.RB_QTableWidget0.set_main_window(self)
        else:
            self.RB_QTableWidget0 = QtWidgets.QTableWidget(self.Right_Bottom_QGroupBox)

        self.RB_QTableWidget0.setObjectName("RB_QTableWidget0")
        self.verticalLayout_3.addWidget(self.RB_QTableWidget0)

        self.RB_Line1 = QtWidgets.QFrame(self.Right_Bottom_QGroupBox)
        self.RB_Line1.setFrameShape(QtWidgets.QFrame.VLine)
        self.RB_Line1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.RB_Line1.setObjectName("RB_Line1")
        self.verticalLayout_3.addWidget(self.RB_Line1)

        # 创建一个新的水平布局
        self.RB_HLayout = QtWidgets.QHBoxLayout()
        self.RB_HLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.RB_HLayout.setObjectName("RB_HLayout")
        
        # 第一个右侧第五行Qlabel
        self.RB_Label1 = QtWidgets.QLabel()
        self.RB_Label1.setObjectName("RB_Label1")
        self.RB_Label1.setSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)  # 设置为可扩展
        self.RB_Label1.setStyleSheet("border: none;background-color: lightblue; border-radius:10px;")
        self.RB_Label1.setAlignment(QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)  # 设置左居中对齐
        self.RB_HLayout.addWidget(self.RB_Label1)
        
        # 第二个右侧第五行Qlabel
        self.RB_Label2 = QtWidgets.QLabel()
        self.RB_Label2.setObjectName("RB_Label2")
        self.RB_Label2.setSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)  # 设置为可扩展
        self.RB_Label2.setStyleSheet("border: none;background-color: lightblue; border-radius:10px;")
        self.RB_Label2.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignVCenter)  # 设置右居中对齐
        self.RB_HLayout.addWidget(self.RB_Label2)
        
        # 将水平布局添加到垂直布局中
        self.verticalLayout_3.addLayout(self.RB_HLayout)
        self.verticalLayout_3.setStretch(0, 10)

        # 设置右侧大的垂直layout--包含控制界面和显示界面
        self.Right_QVBoxLayout.addWidget(self.Right_Bottom_QGroupBox)
        self.Right_QVBoxLayout.setStretch(0, 2)
        self.Right_QVBoxLayout.setStretch(1, 24)

        self.Right_Bottom_QGroupBox.raise_()
        self.Right_Top_QGroupBox.raise_()

        self.gridLayout.addWidget(self.splitter, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.main_body)

        # self.menubar = QtWidgets.QMenuBar(MainWindow)
        # self.menubar.setGeometry(QtCore.QRect(0, 0, 964, 22))
        # self.menubar.setObjectName("menubar")
        # MainWindow.setMenuBar(self.menubar)

        self.splitter.setStretchFactor(0, 1)  # 设置左侧部件（Left_QGroupBox）的拉伸因子为1
        self.splitter.setStretchFactor(1, 2)  # 设置右侧部件（Right_QFrame）的拉伸因子为1

        # 设置分割器的初始大小比例
        self.splitter.setSizes([200, 600])  # 左侧组件初始宽度为300，右侧组件初始宽度为600

        # 设置左侧和右侧组件的最小大小
        self.Left_QGroupBox.setMinimumSize(200, 0)  # 左侧组件的最小宽度
        self.Right_QFrame.setMinimumSize(400, 0)  # 右侧组件的最小宽度

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Left_QGroupBox.setTitle(_translate("MainWindow", "磁盘显示"))
        self.L_radioButton1.setText(_translate("MainWindow", "  显示图片"))
        self.L_radioButton2.setText(_translate("MainWindow", "  显示视频"))
        
        self.Right_Top_QGroupBox.setTitle(_translate("MainWindow", "控制界面"))
        self.RT_QPushButton3.setText(_translate("MainWindow", "清除"))
        self.RT_QPushButton5.setText(_translate("MainWindow", "对比"))

        self.Right_Bottom_QGroupBox.setTitle(_translate("MainWindow", "显示界面"))
        self.RB_Label1.setText(_translate("MainWindow", "第一个标签"))
        self.RB_Label2.setText(_translate("MainWindow", "第二个标签"))



if __name__ == '__main__':
    import sys  # 添加导入

    app = QApplication(sys.argv)  # 创建QApplication实例
    window = QtWidgets.QMainWindow()  # 创建主窗口实例
    ui = Ui_MainWindow()  # 创建UI实例
    ui.setupUi(window)  # 设置UI
    window.show()  # 显示主窗口
    sys.exit(app.exec_())  # 运行应用程序
    